### ISSUE TITLE
First submission requires manual approval

### ISSUE THREAD

**Issue by jasperchui** [openshift-helm-charts/repo#47]
Currently Github Actions require that the first PR submission requires manual approval. 

Investigate if this can be removed.

**Comment by baijum** [comment]
As of now, this feature cannot be disabled. This feature was added as a security measure against malicious usage.

- https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks 
- https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors/

**Comment by jasperchui** [comment]
What mitigation options do we have? How can we get notified if a submission is requiring manual approval? Are there plans to provide an option for the github repo owner to configure this behaviour?

**Comment by baijum** [comment]
I hope we can approve the first-time submitter PR through GitHub Actions using a bot account. Since this feature has been landed very recently (on April 22nd), I couldn't find any existing GitHub Actions that do that. 

I can see some discussions:
* https://github.community/t/how-to-auto-approve-workflow-runs-for-first-time-contributors/176436
* https://github.community/t/this-workflow-is-awaiting-approval-from-a-maintainer/176206

Also, I searched the GitHub Actions API to approve. I am not able to figure out whether this API does the required:
https://docs.github.com/en/rest/reference/actions#review-pending-deployments-for-a-workflow-run

So, this needs further investigation. Let me know the priority so that I can look into that accordingly.

**Comment by baijum** [comment]
* Slack notification and email notification to the team when manual approval is required.

**Comment by baijum** [comment]
Currently notifications and sent to #helm-charts-repo Slack channel and to my email adress.
